Feat(time-range-card): filter by time ranges added
CoronaTeamMOD/CoronaInvestigation pull request #1076
Opened 2021-01-03 15:14 UTC by Noam6421

This PR implements the following feature [1208](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1208/)
In this PR I added filtering option by Time Ranges, the filter is applied both on the admin landing page and on the investigation table.

2021-01-03 15:25 UTC, roymaniv commented on client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/timeRangeFilterCard.tsx
> +                /> */}
remove comment

2021-01-03 15:25 UTC, roymaniv commented on client/src/models/enums/timeRanges.ts
> +    // },
remove comment

2021-01-03 15:25 UTC, roymaniv commented on client/src/models/FilterRulesVariables.ts
> +import { TimeRange } from "./TimeRange";
single quotes

2021-01-03 15:26 UTC, roymaniv commented on client/src/components/App/Content/LandingPage/adminLandingPage/useAdminLandingPage.ts
> +            if(timeRange.id !== 10) {
10 should be in const

2021-01-04 08:27 UTC, y-golde requested changes

2021-01-04 08:27 UTC, y-golde commented on client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/timeRangeFilterCard.tsx
> +                    <Select
separate into a component

2021-01-04 08:45 UTC, Noam6421 commented on client/src/models/FilterRulesVariables.ts
> +import { TimeRange } from "./TimeRange";
👍🏼

2021-01-04 08:45 UTC, Noam6421 commented on client/src/models/enums/timeRanges.ts
> +    // },
👍🏼

2021-01-04 08:45 UTC, Noam6421 commented on client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/timeRangeFilterCard.tsx
> +                /> */}
👍🏼

2021-01-04 08:48 UTC, Noam6421 commented on client/src/components/App/Content/LandingPage/adminLandingPage/useAdminLandingPage.ts
> +            if(timeRange.id !== 10) {
👍🏼

2021-01-04 09:17 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/timeRangeFilterCard.tsx
> +                            onTimeRangeChange(event.target.value as number)
you dont need the curly braces

2021-01-04 09:17 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/timeRangeFilterCard.tsx
> +    const { timeRangeFilter, setTimeRangeFilter, investigationInfoFilter, setInvestigationInfoFilter } = props;
enter

2021-01-04 09:17 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/timeRangeFilterCard.tsx
> +    const { isLoading, onTimeRangeChange, onUpdateButtonCLicked } = useTimeRangeFilterCard({
enter

2021-01-04 09:20 UTC, Noam6421 commented on client/src/components/App/Content/LandingPage/adminLandingPage/TimeRangeFilterCard/timeRangeFilterCard.tsx
> +                    <Select
👍🏼

2021-01-04 09:20 UTC, roymaniv approved these changes

2021-01-04 09:26 UTC, y-golde approved these changes

2021-01-04 09:29 UTC, merged