Feat/admin landing page last updated
CoronaTeamMOD/CoronaInvestigation pull request #1084
Opened 2021-01-04 11:50 UTC by y-golde

added 'last updated by' time in the admin landing page

additionaly , added  `getTimeSinceMessage()` - to display 'X min/sec/etc. ago' messages and a new refresh icon

2021-01-04 12:51 UTC, Noam6421 requested changes

2021-01-04 12:51 UTC, Noam6421 commented on client/src/Utils/DateUtils/timeSince.ts
> +
cancel enter

2021-01-04 12:51 UTC, Noam6421 commented on client/src/Utils/DateUtils/timeSince.ts
> +        return Math.floor(interval) + " " + times.years;
double quotes

2021-01-04 12:51 UTC, Noam6421 commented on client/src/Utils/DateUtils/timeSince.ts
> +        return Math.floor(interval) + " " + times.months;
same

2021-01-04 12:51 UTC, Noam6421 commented on client/src/components/App/Content/LandingPage/adminLandingPage/LastUpdateMessage/lastUpdateMessageStyles.ts
> +
cancel enter

2021-01-04 12:51 UTC, Noam6421 commented on client/src/components/App/Content/LandingPage/adminLandingPage/useAdminLandingPage.ts
> -
enter

2021-01-04 13:48 UTC, y-golde commented on client/src/Utils/DateUtils/timeSince.ts
> +
fixed [here](https://github.com/CoronaTeamMOD/CoronaInvestigation/pull/1084/commits/dc156229e7fae54b50b553f478c413928ef66e08)

2021-01-04 13:48 UTC, y-golde commented on client/src/Utils/DateUtils/timeSince.ts
> +        return Math.floor(interval) + " " + times.years;
fixed [here](https://github.com/CoronaTeamMOD/CoronaInvestigation/pull/1084/commits/dc156229e7fae54b50b553f478c413928ef66e08)

2021-01-04 13:48 UTC, y-golde commented on client/src/Utils/DateUtils/timeSince.ts
> +        return Math.floor(interval) + " " + times.months;
fixed [here](https://github.com/CoronaTeamMOD/CoronaInvestigation/pull/1084/commits/dc156229e7fae54b50b553f478c413928ef66e08)

2021-01-04 13:48 UTC, y-golde commented on client/src/components/App/Content/LandingPage/adminLandingPage/LastUpdateMessage/lastUpdateMessageStyles.ts
> +
fixed [here](https://github.com/CoronaTeamMOD/CoronaInvestigation/pull/1084/commits/dc156229e7fae54b50b553f478c413928ef66e08)

2021-01-04 13:48 UTC, y-golde commented on client/src/components/App/Content/LandingPage/adminLandingPage/useAdminLandingPage.ts
> -
fixed [here](https://github.com/CoronaTeamMOD/CoronaInvestigation/pull/1084/commits/dc156229e7fae54b50b553f478c413928ef66e08)

2021-01-04 13:50 UTC, Noam6421 approved these changes

2021-01-06 07:30 UTC, eladyashar approved these changes

2021-01-06 07:38 UTC, merged