Feat/change user county
CoronaTeamMOD/CoronaInvestigation pull request #1120
Opened 2021-01-07 19:19 UTC by EmilyLip

https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1361 

Admin can change users county , except his

2021-01-07 20:00 UTC, RoeiRom requested changes

2021-01-07 22:40 UTC, EmilyLip commented on client/src/components/App/Content/UsersManagement/useUsersManagement.ts
> +            axios.post('users/updateCounty', {
Agree, but this route already exists (query users by current user\'s county id), so i followed the same way those routes were written:
/users/updateSourceOrganizationById
/users/updateDesk.

We need to change them all, or leave it like it is now

2021-01-08 05:41 UTC, RoeiRom approved these changes

2021-01-09 21:32 UTC, sandymash approved these changes

2021-01-10 05:29 UTC, merged