WIP: feat(Observer.ts): add observer DP
CoronaTeamMOD/CoronaInvestigation pull request #121
Opened 2020-09-12 17:49 UTC by RoeiRom

2020-09-12 20:57 UTC, NaamanTsur requested changes
Honestly I still don't have an understanding of the project to know whether the `observer` pattern is useful here so I won't comment on it at the moment.

2020-09-12 20:57 UTC, NaamanTsur commented on client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
> +        tabsObserver.subscribe(id, () => {
You need to cleanup the event subscription when the component leaves the DOM. Maybe call it `unsubscribe`.

2020-09-12 20:57 UTC, NaamanTsur commented on client/src/commons/ObserverDP/Observer.ts
> +    notifySpecific(id: number) {
I think calling the function `notify` is clear enough, considering there is also a `notifyAll` function.

2020-09-12 20:57 UTC, NaamanTsur commented on client/src/components/App/Content/InvestigationForm/InvestigationForm.tsx
> +                                        //currentTab.id === LAST_TAB_ID ? confirmFinishInvestigation(epidemiologyNumber) : handleSwitchTab();
Remove commented code.

2020-09-12 20:57 UTC, NaamanTsur commented on client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposuresAndFlights.tsx
> +        tabsObserver.subscribe(id, () => {
Same issue here with event cleanup.

2020-09-12 20:57 UTC, NaamanTsur commented on client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
> +        tabsObserver.subscribe(id, () => {
Same issue here with event cleanup.

2020-09-13 10:04 UTC, sandymash commented on client/src/components/App/Content/InvestigationForm/TabManagement/TabManagement.tsx
> +        displayComponent: <ClinicalDetails id={1} />
could take id from existing TabObj id

2020-09-21 06:25 UTC, closed without merging