Feat/grouped contacts icon
CoronaTeamMOD/CoronaInvestigation pull request #1255
Opened 2021-01-27 14:38 UTC by y-golde

Moved grouped investigation state to redux (in order to use the state in both contact questioning and in interactions tab)

added new icon for grouped contact.

2021-01-28 07:39 UTC, Noam6421 requested changes

2021-01-28 07:39 UTC, Noam6421 commented on client/src/components/App/Content/InvestigationForm/useGroupedInvestigationContacts.ts
> +                        displayName : "טוען..."
replace with ingle quotes

2021-01-28 07:39 UTC, Noam6421 commented on client/src/components/App/Content/InvestigationForm/useGroupedInvestigationContacts.ts
> +
delete empty row

2021-01-28 07:39 UTC, Noam6421 commented on client/src/redux/GroupedInvestigations/GroupedInvestigationsActionTypes.ts
> +export const SET_GROUPED_INVESTIGATIONS = 'SET_GROUPED_INVESTIGATIONS';
add empty row

2021-01-28 07:39 UTC, Noam6421 commented on client/src/redux/GroupedInvestigations/GroupedInvestigationsType.ts
> +    groupId : "",
single quotes

2021-01-28 07:39 UTC, Noam6421 commented on client/src/redux/GroupedInvestigations/GroupedInvestigationsType.ts
> +            displayName : "טוען..."
same

2021-01-28 13:51 UTC, y-golde commented on client/src/redux/GroupedInvestigations/GroupedInvestigationsType.ts
> +            displayName : "טוען..."
fixed [here](https://github.com/CoronaTeamMOD/CoronaInvestigation/pull/1255/commits/e0ec564a60582787ff95dc9832adeafe29c253e3)

2021-01-28 13:51 UTC, y-golde commented on client/src/redux/GroupedInvestigations/GroupedInvestigationsType.ts
> +    groupId : "",
fixed [here](https://github.com/CoronaTeamMOD/CoronaInvestigation/pull/1255/commits/e0ec564a60582787ff95dc9832adeafe29c253e3)

2021-01-28 13:51 UTC, y-golde commented on client/src/redux/GroupedInvestigations/GroupedInvestigationsActionTypes.ts
> +export const SET_GROUPED_INVESTIGATIONS = 'SET_GROUPED_INVESTIGATIONS';
fixed [here](https://github.com/CoronaTeamMOD/CoronaInvestigation/pull/1255/commits/e0ec564a60582787ff95dc9832adeafe29c253e3)

2021-01-28 13:52 UTC, y-golde commented on client/src/components/App/Content/InvestigationForm/useGroupedInvestigationContacts.ts
> +
fixed [here](https://github.com/CoronaTeamMOD/CoronaInvestigation/pull/1255/commits/e0ec564a60582787ff95dc9832adeafe29c253e3)

2021-01-28 13:52 UTC, y-golde commented on client/src/components/App/Content/InvestigationForm/useGroupedInvestigationContacts.ts
> +                        displayName : "טוען..."
fixed [here](https://github.com/CoronaTeamMOD/CoronaInvestigation/pull/1255/commits/e0ec564a60582787ff95dc9832adeafe29c253e3)

2021-01-28 14:05 UTC, Noam6421 submitted a review, later dismissed

2021-01-31 07:55 UTC, chenFriedman approved these changes

2021-01-31 07:57 UTC, Noam6421 approved these changes

2021-01-31 07:57 UTC, merged