feat(deactivate-all-county-users)
CoronaTeamMOD/CoronaInvestigation pull request #1268
Opened 2021-01-31 13:24 UTC by Noam6421

Added to Test, US [1485](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1485/)

2021-01-31 13:32 UTC, y-golde approved these changes

2021-02-01 05:23 UTC, RoeiRom requested changes

2021-02-01 05:23 UTC, RoeiRom commented on client/src/components/App/Content/UsersManagement/useUsersManagement.ts
> +                .finally(() => setIsLoading(false));
Doesn’t need to be in finally, only in catch, because fetchUsers will turn the spinner off

2021-02-01 07:20 UTC, y-golde approved these changes

2021-02-01 07:22 UTC, RoeiRom approved these changes

2021-02-01 07:23 UTC, merged