1619/feat/edit-static-fields-for-admins
CoronaTeamMOD/CoronaInvestigation pull request #1432
Opened 2021-03-16 15:50 UTC by Noam6421

## This PR Implements Feature: [1619](https://dev.azure.com/spectrumFactory/CoronaI/_sprints/backlog/CoronaI%20Team/CoronaI/Sprint%2016?workitem=1619)

### What in this PR? 
* Separate status section to it's own component

* New route:
POST /investigationInfo/updateStaticInfo

* New DB function- update_static_info:

1. updates according to the request one of the following  fields: fullName,  identificationType, identityNumber.
2. according to the investigation status also changes end_time or lasr_update_time.

* Added static fields form that currently enable editing the investigated fullName but also supports editing identificationType and identityNumber (those are currently disabled due to PM request)

2021-03-16 18:05 UTC, MagusM approved these changes

2021-03-16 19:52 UTC, chenFriedman commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> +import { Edit, CakeOutlined, EventOutlined, Help, CalendarToday } from '@material-ui/icons';
I'm not sure that there is any need for this icons because I removed this line

2021-03-16 19:56 UTC, chenFriedman commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> -        <Paper className={classes.paper}>
I need to add this  line       <Paper className={classes.paper}>
because i used it to align the items

2021-03-16 20:03 UTC, chenFriedman commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> +                                    <PatientInfoItem testId='age' name='גיל' value={+age < 1 ? 'פחות משנה' : age} />
this area looks the same I'm not sure why it got changed

2021-03-16 20:05 UTC, chenFriedman commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> +                                            investigationStatus.subStatus === InvestigationComplexityByStatus.IS_DECEASED)) &&
you can move the long conditions to const with a name that will describe the codition

2021-03-16 20:05 UTC, chenFriedman commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> +                                        (investigationStatus.mainStatus === InvestigationMainStatusCodes.CANT_COMPLETE &&
you can move the long conditions to const with a name that will describe the condition

2021-03-16 20:07 UTC, chenFriedman commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> +                                <Tooltip title={isVaccinated ? vaccinationEffectiveFrom ? formatDate(vaccinationEffectiveFrom) : noInfo : ''}>
i had to remove all tooltip except for complexity start

2021-03-16 20:08 UTC, chenFriedman commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> +                                    isVaccinated && <ComplexityIcon tooltipText={formatDate(vaccinationEffectiveFrom)} />
I had to remove all tooltip except for complexity start

2021-03-16 20:08 UTC, chenFriedman commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> +                                <Tooltip title={isSuspicionOfMutation ? mutationName ? mutationName : noInfo : ''}>
same

2021-03-16 20:08 UTC, chenFriedman commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> +                                <Tooltip title={isReturnSick ? previousDiseaseStartDate ? formatDate(previousDiseaseStartDate) : noInfo : ''} >
same

2021-03-17 07:41 UTC, y-golde requested changes

2021-03-17 07:41 UTC, y-golde commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfoInterfaces.ts
> +    staticFieldsSubmit: (data: any) => void;
why any

2021-03-17 07:41 UTC, y-golde commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationStatusInfo/InvestigationStatusInfo.tsx
> +                                        error={statusReasonError ? true : false}
why not Boolean lol?

2021-03-17 07:41 UTC, y-golde commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationStatusInfo/InvestigationStatusInfoStyles.ts
> +        alignItems: 'center',
Switch to Grid with props

2021-03-17 07:41 UTC, y-golde commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationStatusInfo/InvestigationStatusInfoStyles.ts
> +    },
remove

2021-03-17 07:41 UTC, y-golde commented on db scripts/update_static_info.sql
> +	if status = 100000001 then
use Elsif https://www.postgresql.org/docs/9.1/plpgsql-control-structures.html

2021-03-17 08:46 UTC, Noam6421 commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigatedPersonInfo.tsx
> +                                                label={get(methods.errors, props.name)?.message || ''}
changed it

2021-03-17 08:51 UTC, Noam6421 commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationStatusInfo/InvestigationStatusInfo.tsx
> +                                        error={statusReasonError ? true : false}
Fixed

2021-03-17 08:52 UTC, Noam6421 commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigatedPersonInfo/InvestigationStatusInfo/InvestigationStatusInfoStyles.ts
> +    },
removed

2021-03-17 09:10 UTC, chenFriedman submitted a review, later dismissed

2021-03-17 09:11 UTC, chenFriedman approved these changes

2021-03-17 09:12 UTC, y-golde approved these changes

2021-03-17 09:13 UTC, merged