1706/feat/places-new-questions
CoronaTeamMOD/CoronaInvestigation pull request #1490
Opened 2021-04-08 16:46 UTC by Noam6421

## This PR Implements Feature: [1706](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1706/)

### What in this PR? 
* New fields in Interactions Tab about green pass information.

* New & Edit routes:
1. NEW- GET /interactions/greenPassQuestions
2. NEW- GET /interactions/greenPassAnswers
3. EDIT- POST /intersections/updateContactEvent 
4. EDIT- GET /intersections/contactEvents/{date}

* New DB function- update_green_pass_information
* Edit DB function- update_contact_event_function

* New DB Tables: 
1. green_pass_questions
2. green_pass_answers
3. green_pass_information

* Styles to Interactions Tab Form.

2021-04-08 18:25 UTC, chenFriedman approved these changes

2021-04-11 06:14 UTC, y-golde requested changes

2021-04-11 06:14 UTC, y-golde commented on client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionDialog.tsx
> +                    let answerId = +(data as any)[field];
parseInt instead of +

2021-04-11 06:14 UTC, y-golde commented on client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionDialog/InteractionEventForm/InteractionSection/GreenPass/GreenPassInterfaces.ts
> +    greenPass: {[key: number] : number};
you can use Record<number,number> BTW

2021-04-11 06:15 UTC, y-golde approved these changes

2021-04-11 06:16 UTC, merged