1725/fix/tabs-height
CoronaTeamMOD/CoronaInvestigation pull request #1501
Opened 2021-04-12 12:26 UTC by chenFriedman

2021-04-12 12:31 UTC, barnahum8 approved these changes

2021-04-12 12:32 UTC, y-golde requested changes
![image](https://user-images.githubusercontent.com/68457306/114394753-37eaab00-9ba4-11eb-83fc-9378852ac232.png)
it leaved this big empty space

2021-04-12 12:32 UTC, Noam6421 submitted a review, later dismissed

2021-04-12 12:33 UTC, y-golde commented
![image](https://user-images.githubusercontent.com/68457306/114394847-5b155a80-9ba4-11eb-9338-6a972e83fa98.png)
script is missing padding

2021-04-13 06:28 UTC, y-golde approved these changes

2021-04-13 06:38 UTC, Noam6421 approved these changes

2021-04-13 06:38 UTC, merged