1529/feat/app tool bar tests
CoronaTeamMOD/CoronaInvestigation pull request #1519
Opened 2021-04-21 08:25 UTC by Noam6421

In this PR I started writing tests for the AppToolbar component.

2021-04-21 11:05 UTC, y-golde requested changes

2021-04-21 11:05 UTC, y-golde commented on client/src/components/App/AppToolbar/AppToolbar.test.tsx
> +    // });
remove

2021-04-21 11:05 UTC, y-golde commented on client/src/Utils/Testing/AppToolbar/mockUseAppToolbar.ts
> +
remove one space

2021-04-22 05:42 UTC, Noam6421 commented on client/src/Utils/Testing/AppToolbar/mockUseAppToolbar.ts
> +
removed one line

2021-04-22 05:42 UTC, Noam6421 commented on client/src/components/App/AppToolbar/AppToolbar.test.tsx
> +    // });
removed it

2021-04-22 05:48 UTC, y-golde approved these changes

2021-04-22 05:55 UTC, barnahum8 approved these changes

2021-04-22 05:55 UTC, merged