feat(date-picker): use material-ui date picker
CoronaTeamMOD/CoronaInvestigation pull request #220
Opened 2020-09-17 20:17 UTC by nevobonneh

This pull request switches the use of textfield with type date/time into mui's pickers

2020-09-17 20:27 UTC, NaamanTsur requested changes

2020-09-17 20:27 UTC, NaamanTsur commented on client/src/commons/DatePick/DatePick.tsx
> +    <MuiPickersUtilsProvider utils={DateFnsUtils} locale={heLocale}>
The utils provider needs to sit at the root of the component tree, not each date picker

2020-09-17 20:27 UTC, NaamanTsur commented on client/src/commons/DatePick/TimePick.tsx
> +    <MuiPickersUtilsProvider utils={DateFnsUtils} locale={heLocale}>
Move this provider as well

2020-09-17 20:37 UTC, NaamanTsur submitted a review, later dismissed

2020-09-21 06:18 UTC, MayaSasson commented on client/src/commons/DatePick/DatePick.tsx
> +import { ParsableDate } from "@material-ui/pickers/constants/prop-types";
imports order

2020-09-21 06:19 UTC, MayaSasson commented on client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
> +import useClinicalDetails from "./useClinicalDetails";
change to single quote in all imports

2020-09-21 06:22 UTC, MayaSasson commented on client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
> +import PlacesTypesAndSubTypes from "commons/Forms/PlacesTypesAndSubTypes/PlacesTypesAndSubTypes";
single quotes and imports order

2020-09-21 06:23 UTC, MayaSasson commented on client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightsForm.tsx
> +import AirportInput from "./AirportInput/AirportInput";
single quotes

2020-09-21 06:33 UTC, ItayBenMoshe commented on client/src/commons/DatePick/TimePick.tsx
> +const DatePick: React.FC<Props> = (props: Props): JSX.Element => {
I think that the component name should be TimePick instead of DatePick

2020-09-21 06:33 UTC, ItayBenMoshe commented on client/src/commons/DatePick/TimePick.tsx
> +export default DatePick;
Also here

2020-09-21 08:14 UTC, closed without merging