fix(spaces):
CoronaTeamMOD/CoronaInvestigation pull request #236
Opened 2020-09-21 15:45 UTC by daniel7764

-Refactored all the spaces and placing of fields across the forms

2020-09-21 16:59 UTC, sandymash commented on client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
> +                                className={classes.textField}
property textField doesnt exist on new styles

2020-09-21 18:08 UTC, sandymash approved these changes

2020-09-22 11:11 UTC, OrelKaravani requested changes

2020-09-23 16:23 UTC, sandymash commented on client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
> +                            כתובת לאשפוז ביתי:
![image](https://user-images.githubusercontent.com/42100027/94040950-42914e80-fdd2-11ea-8e70-853554b5d1f3.png)
addres fields overlap in ckinical details tab

2020-09-23 16:27 UTC, sandymash commented on client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/FlightsForm/FlightsForm.tsx
> +                <FormRowWithInput fieldName="יעד:">
![image](https://user-images.githubusercontent.com/42100027/94041269-af0c4d80-fdd2-11ea-85c7-5ca61345cb52.png)
fields are too small here

2020-09-23 16:28 UTC, sandymash commented on client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
>                                  label='סוג מגע'
![image](https://user-images.githubusercontent.com/42100027/94041485-f4307f80-fdd2-11ea-93d4-dd31a373a983.png)
label is in weird position

2020-09-23 19:26 UTC, closed without merging