Feat/alphanumeric text field in tab
CoronaTeamMOD/CoronaInvestigation pull request #251
Opened 2020-09-22 18:53 UTC by NaamanTsur

This pull request implements the `AlphanumericTextField` component in all the forms. This accomplishes prevention of typing non alphanumerical values into text fields (!@#$_+ etc.). This is not a full form implementation, only text field prevention.

2020-09-22 19:12 UTC, eladyashar commented on client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
> -            required
need to mark as required and removed

2020-09-22 19:12 UTC, eladyashar commented on client/src/components/App/Content/InvestigationForm/TabManagement/ExposuresAndFlights/ExposureForm/ExposureForm.tsx
> -            required
required here to

2020-09-22 19:42 UTC, eladyashar commented on client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
> -                        required
add required

2020-09-22 19:42 UTC, eladyashar commented on client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
> -                        required
add required and label

2020-09-22 19:52 UTC, eladyashar submitted a review, later dismissed

2020-09-23 05:52 UTC, RoeiRom requested changes

2020-09-23 05:52 UTC, RoeiRom commented on client/src/commons/AlphanumericTextField/AlphanumericTextField.tsx
> +          const isValid = await stringAlphanum.isValid(newValue);
זה לא יאט את הפעילות של המשתמש שכל פעם שהוא מקיש יש פעולה אסינכרונית שמחכים שתסתיים?

2020-09-23 05:52 UTC, RoeiRom commented on client/src/commons/AlphanumericTextField/AlphanumericTextField.tsx
> +            clearErrors(name);
למה שיהיה ניקוי של השגיאות ולא קריאה לonBlur שיש בprops

2020-09-23 05:52 UTC, RoeiRom commented on client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/ClinicalDetails.tsx
> +            <form>
חייב את התגית form?

2020-09-23 05:52 UTC, RoeiRom commented on client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
> +                        onChange={newValue => onChange(newValue, InteractionEventContactFields.FIRST_NAME)}
tab

2020-09-23 05:52 UTC, RoeiRom commented on client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/InteractionEventForm/ContactForm/ContactForm.tsx
> +                        onChange={newValue => onChange(newValue, InteractionEventContactFields.LAST_NAME)}
same

2020-09-23 05:52 UTC, RoeiRom commented on client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
>                          }}
untab

2020-09-23 06:10 UTC, NaamanTsur commented on client/src/commons/AlphanumericTextField/AlphanumericTextField.tsx
> +          const isValid = await stringAlphanum.isValid(newValue);
Fixed by using `isValidSync` instead

2020-09-23 08:08 UTC, RoeiRom approved these changes

2020-09-23 08:11 UTC, eladyashar approved these changes

2020-09-23 08:15 UTC, merged