feat(disable-fields-when-reopen): disabling fields when reopening investigation
CoronaTeamMOD/CoronaInvestigation pull request #647
Opened 2020-11-01 16:16 UTC by MayaSasson

2020-11-01 16:46 UTC, ItayBenMoshe commented on client/src/redux/Investigation/investigationActionTypes.ts
> +
delete extra row

2020-11-01 17:25 UTC, ItayBenMoshe approved these changes

2020-11-02 08:07 UTC, RoeiRom requested changes

2020-11-02 08:07 UTC, RoeiRom commented on client/src/components/App/Content/InvestigationForm/TabManagement/ClinicalDetails/SymptomsFields.tsx
> +    const wasInvestigationReopend = endTime !== null;
you can do the condition in one line

2020-11-02 08:26 UTC, RoeiRom approved these changes

2020-11-02 08:27 UTC, ItayBenMoshe approved these changes

2020-11-02 08:28 UTC, merged