fix(UsersManagement):fix sort by username(bug #902)
CoronaTeamMOD/CoronaInvestigation pull request #739
Opened 2020-11-12 18:50 UTC by doronlnd84

2020-11-12 21:32 UTC, RoeiRom requested changes

2020-11-12 21:32 UTC, RoeiRom commented on client/src/components/App/Content/UsersManagement/useUsersManagement.ts
> +import {UsersManagementTableHeadersNames } from './UsersManagementTableHeaders';
add space

2020-11-12 21:32 UTC, RoeiRom commented on client/src/components/App/Content/UsersManagement/useUsersManagement.ts
> +    const fillEmptyfullName= (users: any[]):SignUpUser[]=>{
add space

2020-11-12 21:32 UTC, RoeiRom commented on client/src/components/App/Content/UsersManagement/useUsersManagement.ts
> +        users.forEach(user=> {
add space

2020-11-12 21:32 UTC, RoeiRom commented on client/src/components/App/Content/UsersManagement/useUsersManagement.ts
> +            if(!Boolean(user.fullName)){
Boolean is not needed

2020-11-12 21:32 UTC, RoeiRom commented on client/src/components/App/Content/UsersManagement/useUsersManagement.ts
> +    const fillEmptyfullName= (users: any[]):SignUpUser[]=>{
add type

2020-11-15 07:38 UTC, ItayBenMoshe requested changes

2020-11-15 07:38 UTC, ItayBenMoshe commented on client/src/components/App/Content/UsersManagement/useUsersManagement.ts
> +import {UsersManagementTableHeadersNames } from './UsersManagementTableHeaders';
imports order

2020-11-15 08:47 UTC, ItayBenMoshe approved these changes

2020-11-16 07:54 UTC, daniel7764 submitted a review, later dismissed

2020-11-16 13:38 UTC, RoeiRom approved these changes

2020-11-16 13:40 UTC, daniel7764 approved these changes

2020-11-17 10:32 UTC, closed without merging

2020-11-17 10:32 UTC, doronlnd84 commented
האיפיון שונה