change logs to the new method that naaman wrote
CoronaTeamMOD/CoronaInvestigation pull request #764
Opened 2020-11-16 17:04 UTC by ItayBenMoshe

2020-11-16 17:10 UTC, NaamanTsur requested changes

2020-11-16 17:10 UTC, NaamanTsur commented on client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ExcelUploader/ContactUploader.tsx
> +            const DataInFileLogger = logger.setup({
Change from pascal case to canal case

2020-11-16 17:10 UTC, NaamanTsur commented on client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
> +            const ContactLogger = logger.setup({
Change from pascal case to camal case

2020-11-16 17:10 UTC, NaamanTsur commented on client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
> +        const InteractedContactsLogger = logger.setup({
Pascal to camal case

2020-11-16 17:10 UTC, NaamanTsur commented on client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
> +        const FamilyRelationshipsLogger = logger.setup({
Pascal to camal case

2020-11-16 17:10 UTC, NaamanTsur commented on client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
> +        const ContactStatusesLogger = logger.setup({
Pascal to camal case

2020-11-17 08:24 UTC, ItayBenMoshe commented on client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/ContactDateCard/InteractionCard/ExcelUploader/ContactUploader.tsx
> +            const DataInFileLogger = logger.setup({
fixed

2020-11-17 08:24 UTC, ItayBenMoshe commented on client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
> +            const ContactLogger = logger.setup({
fixed

2020-11-17 08:24 UTC, ItayBenMoshe commented on client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
> +        const InteractedContactsLogger = logger.setup({
fixed

2020-11-17 08:24 UTC, ItayBenMoshe commented on client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
> +        const FamilyRelationshipsLogger = logger.setup({
fixed

2020-11-17 08:24 UTC, ItayBenMoshe commented on client/src/components/App/Content/InvestigationForm/TabManagement/ContactQuestioning/useContactQuestioning.ts
> +        const ContactStatusesLogger = logger.setup({
fixed

2020-11-17 08:25 UTC, NaamanTsur approved these changes

2020-11-17 08:28 UTC, nevobonneh approved these changes

2020-11-17 08:28 UTC, merged