WIP: Fix(update-grouped-investigations) - Add update option in order to add non grouped investigations to an existing group
CoronaTeamMOD/CoronaInvestigation pull request #888
Opened 2020-12-03 15:40 UTC by nevobonneh

2020-12-03 17:49 UTC, ItayBenMoshe requested changes

2020-12-03 17:49 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/useGroupedInvestigations.ts
> +            const invetigationsToGroupIds = invetigationsToGroup.map((invetigationToGroup: InvestigationTableRow) => invetigationToGroup.epidemiologyNumber);
you use `invetigationsToGroupIds` twice (you do the same action also in line 63)
move it out from the if else case

2020-12-03 17:49 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/useGroupedInvestigations.ts
> +        const groupIdsWithRepeation = invetigationsToGroup.map((invetigationToGroup: InvestigationTableRow) => invetigationToGroup.groupId);
change the name to `groupIds`

2020-12-03 17:49 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/useGroupedInvestigations.ts
> +        const groupIdsWithoutRepeation = groupIdsWithRepeation.filter((item, pos) => groupIdsWithRepeation.indexOf(item) === pos && item !== null);
change the name to `trimedGroupidIds`.
anotehr way to do it is `Array.from(new Set(groupIds)).filter((groupId: string) => groupId)`

2020-12-03 17:49 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/useGroupedInvestigations.ts
> +        const groupIdsWithoutRepeation = groupIdsWithRepeation.filter((item, pos) => groupIdsWithRepeation.indexOf(item) === pos && item !== null);
why do you filter the null? null means investigation without group

2020-12-03 17:49 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/useGroupedInvestigations.ts
> +            axios.post('/groupedInvestigations', { group, invetigationsToGroupIds, createOrUpdate })
I don't think you need createOrUpdate parameter.
you pass group as object if you create the group and group as id if you update the grouped investigations. consider it

2020-12-07 10:35 UTC, MayaSasson requested changes

2020-12-07 10:35 UTC, MayaSasson commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/useGroupedInvestigations.ts
> +        if (trimedGroupidIds.length === 2 && trimedGroupidIds.findIndex((groupId: string) => groupId === null) > -1) {
I think !=-1 is clearer

2020-12-07 10:35 UTC, MayaSasson commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/useGroupedInvestigations.ts
> +        if (trimedGroupidIds.length === 2 && trimedGroupidIds.findIndex((groupId: string) => groupId === null) > -1) {
I would do include here anyway

2020-12-07 10:35 UTC, MayaSasson commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooter.tsx
> +        return trimedGroupidIds.length > 2 || (trimedGroupidIds.findIndex((groupId: string) => groupId === null) === -1) || checkedInvestigations.length < 2
The number two is also used on another place. To make it clearer I would export it to a const and use it on both places

2020-12-07 10:35 UTC, MayaSasson commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/InvestigationTableFooter.tsx
> +        return trimedGroupidIds.length > 2 || (trimedGroupidIds.findIndex((groupId: string) => groupId === null) === -1) || checkedInvestigations.length < 2
In addition change include here as well

2020-12-07 14:54 UTC, ItayBenMoshe requested changes

2020-12-07 14:54 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/GroupedInvestigationsForm/GroupedInvestigationsForm.tsx
> +                                        onChange={(event) => {
you can delete the curly braces

2020-12-07 14:54 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/GroupedInvestigations.tsx
> +        .find((investigation: InvestigationTableRow) => investigation.groupId !== null);
maybe put it inside useMemo and return boolean instead of array and change the name properly

2020-12-07 14:54 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/GroupedInvestigations/GroupedInvestigations.tsx
> +        .find((investigation: InvestigationTableRow) => investigation.groupId !== null);
also enter

2020-12-07 15:55 UTC, MayaSasson approved these changes

2020-12-07 16:30 UTC, MayaSasson approved these changes

2020-12-07 16:39 UTC, ItayBenMoshe approved these changes

2020-12-07 16:40 UTC, merged