fix(static info): fixes according to new db
CoronaTeamMOD/CoronaInvestigation pull request #91
Opened 2020-09-09 14:33 UTC by yaniryos

2020-09-09 14:52 UTC, OrelKaravani requested changes

2020-09-09 14:52 UTC, OrelKaravani commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
> +        id: 1,
למה זה מאותחל ב- 1?

2020-09-09 14:52 UTC, OrelKaravani commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
> +        investigationGroup: 1
כנ"ל

2020-09-09 14:52 UTC, OrelKaravani commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
> +        id: 1,
כנ"ל

2020-09-09 14:52 UTC, OrelKaravani commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
> +        investigationGroup: 1
כנ"ל

2020-09-09 14:52 UTC, OrelKaravani commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationMetadata/InvestigationMetadata.tsx
>              <InfoItem name='נפח/מחוז' value={investigationMetaData.investigatingUnit} />
תקן על הדרך את הטעות של "נפח" שיהיה נפה

2020-09-09 14:52 UTC, OrelKaravani commented on client/src/models/InvestigatedPatientByInvestigatedPatientId.ts
> +}
לא צריכים עוד דברים? או שזה ייבנה תוך כדי?

2020-09-09 14:52 UTC, OrelKaravani commented on client/src/models/StaticUser.ts
> +    id: number,
בטוח שזה number?

2020-09-09 14:52 UTC, OrelKaravani commented on server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
> +    console.log("HI")
צריך את זה?

2020-09-09 15:25 UTC, yaniryos commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
> +        id: 1,
סתם ערך. לשנות למינוס 1?

2020-09-09 15:25 UTC, yaniryos commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationMetadata/InvestigationMetadata.tsx
>              <InfoItem name='נפח/מחוז' value={investigationMetaData.investigatingUnit} />
טיל

2020-09-09 15:25 UTC, yaniryos commented on client/src/models/InvestigatedPatientByInvestigatedPatientId.ts
> +}
לא צריך

2020-09-09 15:26 UTC, yaniryos commented on server/src/ClientToDBAPI/InvestigationInfo/mainRoute.ts
> +    console.log("HI")
לא

2020-09-09 15:26 UTC, yaniryos commented on client/src/models/StaticUser.ts
> +    id: number,
אני אבדוק

2020-09-09 18:34 UTC, OrelKaravani approved these changes

2020-09-10 06:17 UTC, MayaSasson commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
> +        id: '',
I would create a default user

2020-09-10 06:17 UTC, MayaSasson commented on client/src/components/App/Content/InvestigationForm/InvestigationInfo/InvestigationInfoBar.tsx
> +            console.log(result)
Remove

2020-09-10 06:17 UTC, MayaSasson commented on client/src/models/InvestigatedPatientByInvestigatedPatientId.ts
> +    personByPersonId: Person,
Why can’t it just be person?

2020-09-10 07:03 UTC, OrelKaravani approved these changes

2020-09-10 07:57 UTC, MayaSasson approved these changes

2020-09-10 07:58 UTC, merged