Cities redux
CoronaTeamMOD/CoronaInvestigation pull request #96
Opened 2020-09-09 18:13 UTC by EmilyLip

Added cities to redux, loaded from db on personal info tab .

2020-09-09 18:46 UTC, ShiranEyal submitted a review, later dismissed

2020-09-09 19:33 UTC, OrelKaravani requested changes

2020-09-09 19:33 UTC, OrelKaravani commented on client/src/redux/City/cityReducer.ts
> +            console.log( Actions.SET_CITIES );
Is that necessary?

2020-09-09 19:34 UTC, EmilyLip commented on client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
> +        //axios.get('/intersections?epidemioligyNumber=111').then(res => console.log(res));
not mine and throws error

2020-09-09 19:34 UTC, EmilyLip commented on client/src/redux/City/cityReducer.ts
> +            console.log( Actions.SET_CITIES );
what do you mean?

2020-09-09 19:36 UTC, OrelKaravani commented on client/src/redux/City/cityReducer.ts
> +            console.log( Actions.SET_CITIES );
The console.log line

2020-09-09 19:37 UTC, EmilyLip commented on client/src/redux/City/cityReducer.ts
> +            console.log( Actions.SET_CITIES );
no

2020-09-09 19:37 UTC, OrelKaravani commented on client/src/components/App/Content/InvestigationForm/TabManagement/InteractionsTab/useInteractionsTab.ts
> +        //axios.get('/intersections?epidemioligyNumber=111').then(res => console.log(res));
So I think it's better delete it and keeps the comment

2020-09-09 19:40 UTC, OrelKaravani submitted a review, later dismissed

2020-09-09 20:17 UTC, ShiranEyal submitted a review, later dismissed

2020-09-10 06:02 UTC, MayaSasson commented on client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
> -import React from 'react';
I think the axios supposed  to be inside the investigation form component because this is the general component that contains all the tabs

2020-09-10 06:02 UTC, MayaSasson commented on client/src/components/App/Content/InvestigationForm/TabManagement/PersonalInfoTab/PersonalInfoTab.tsx
> +            result.data.forEach((city: City) => {
Why using a map?

2020-09-10 06:25 UTC, OrelKaravani reviewed
There are discussion to be solved

2020-09-10 09:00 UTC, NaamanTsur requested changes

2020-09-10 09:00 UTC, NaamanTsur commented on client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
> +        axios.get('/addressDetails/cities')
See the redux thunk documentation for more information

2020-09-10 09:14 UTC, MayaSasson submitted a review, later dismissed

2020-09-10 09:14 UTC, ShiranEyal approved these changes

2020-09-10 09:15 UTC, EmilyLip commented on client/src/components/App/Content/InvestigationForm/useInvestigationForm.ts
> +        axios.get('/addressDetails/cities')
after the MVP we will talk about it. please resolve

2020-09-10 09:46 UTC, roymaniv approved these changes

2020-09-10 09:47 UTC, ShiranEyal approved these changes

2020-09-10 10:17 UTC, EmilyLip commented
feat(Cities redux): added cities to redux, loaded from db

2020-09-10 10:32 UTC, EmilyLip commented
feat(Cities redux): Client - added cities to redex. Server - added cities and city streets route with db queries

2020-09-10 10:33 UTC, merged