Feat(InvestigationTable): Modify columns
CoronaTeamMOD/CoronaInvestigation pull request #971
Opened 2020-12-20 16:01 UTC by doronlnd84

For  user stories:
1. 1158 - add SubOccupation (מוסד) column
2. 1128 - remove Priority column
3. 1149 - remove County column

2020-12-20 16:26 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
> +    // [TableHeadersNames.county]: 'נפה מבצעת',
why comment?

2020-12-20 16:37 UTC, ItayBenMoshe requested changes

2020-12-20 16:37 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
> +                                const subOccupation=  investigation?.investigatedPatientByInvestigatedPatientId?.subOccupationBySubOccupation?.displayName;
space before = and delete one space after like that:
`subOccupation = investigation?.investigatedPatientByInvestigatedPatientId...`

2020-12-20 16:37 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
> +                                const parentOccupation=  investigation?.investigatedPatientByInvestigatedPatientId?.subOccupationBySubOccupation?.parentOccupation;
same

2020-12-20 16:37 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTablesHeaders.ts
> +
delete rows

2020-12-20 16:37 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
> +                                                            getTableCell(key, indexedRow,index)
space after ,

2020-12-20 16:37 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
> +                                                                        getTableCell(key, indexedGroupedInvestigationRow,index)
same

2020-12-20 16:37 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
> +                  return    <Tooltip title={parentOccupation} placement="top">
single quote 
`placement='top'`

2020-12-20 16:37 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
> +                        const subOccupation=  investigation?.investigatedPatientByInvestigatedPatientId?.subOccupationBySubOccupation?.displayName;
same

2020-12-20 16:37 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
> +                        const parentOccupation=  investigation?.investigatedPatientByInvestigatedPatientId?.subOccupationBySubOccupation?.parentOccupation;
same

2020-12-21 08:51 UTC, ItayBenMoshe approved these changes

2020-12-21 11:55 UTC, MayaSasson submitted a review, later dismissed

2020-12-21 12:38 UTC, OrelKaravani approved these changes

2020-12-21 12:39 UTC, roymaniv approved these changes

2020-12-21 12:40 UTC, merged