feat(investigation table)
CoronaTeamMOD/CoronaInvestigation pull request #972
Opened 2020-12-21 12:56 UTC by sandymash

- moved complexity & transfer icon indicators to separate column

2020-12-22 11:54 UTC, NaamanTsur requested changes

2020-12-22 11:54 UTC, NaamanTsur commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
> +import {Refresh, Warning, Close, KeyboardArrowDown, KeyboardArrowLeft, Search, ReplyAll} from '@material-ui/icons';
Is there a need for the ReplyAll icon?

2020-12-23 10:27 UTC, sandymash commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTable.tsx
> +import {Refresh, Warning, Close, KeyboardArrowDown, KeyboardArrowLeft, Search, ReplyAll} from '@material-ui/icons';
nope

2020-12-23 10:47 UTC, doronlnd84 approved these changes

2020-12-23 10:53 UTC, NaamanTsur approved these changes

2020-12-23 11:55 UTC, merged