Feat(transfer investigation)
CoronaTeamMOD/CoronaInvestigation pull request #978
Opened 2020-12-22 12:26 UTC by nevobonneh

This PR implements the following feature [1175](https://dev.azure.com/spectrumFactory/CoronaI/_workitems/edit/1075/)
In this PR we added Tabs to TransferInvestigation option on TableFooter. One Tab for  multi transfering between Desks (this was the option that already exists) and the other Tab for multi Transfering between Counties.

2020-12-22 13:50 UTC, ItayBenMoshe requested changes

2020-12-22 13:50 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationTabs.tsx
> +    index: any;
why any?

2020-12-22 13:50 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationTabs.tsx
> +    value: any;
same

2020-12-22 13:50 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationTabs.tsx
> +    const { allDesks, allCounties, onClose, onDeskTransfer, onCountyTransfer } = props;
maybe move it to the top of the component

2020-12-22 13:50 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
> +    const changeGroupsCounty = async (groupIds: string[], newSelectedCounty: County | null, transferReason: string) => {
you used async but didn't use await

2020-12-22 13:50 UTC, ItayBenMoshe commented on client/src/components/App/Content/LandingPage/InvestigationTable/useInvestigationTable.ts
> +    const changeInvestigationCounty = async (epidemiologyNumbers: number[], newSelectedCounty: County | null, transferReason: string) => {
same

2020-12-22 13:50 UTC, ItayBenMoshe commented on server/src/ClientToDBAPI/UsersRoute/mainRoute.ts
> +    Promise.all(epidemiologyNumbers.map(epidemiologyNumber => graphqlRequest(UPDATE_COUNTY_BY_USER, response.locals, {
why mapping the epidemiologyNumbers and execute UPDATE_COUNTY_BY_USER for each epidemiologyNumber
why not changing the query (trying to use IN syntax in sql)

2020-12-23 09:57 UTC, ItayBenMoshe approved these changes

2020-12-23 10:01 UTC, NaamanTsur requested changes

2020-12-23 10:02 UTC, NaamanTsur commented on client/src/components/App/Content/LandingPage/InvestigationTable/InvestigationTableFooter/TransferInvestigationsDialogs/TransferInvestigationTabs.tsx
> +    const StyledTab = withStyles((theme) =>
Not necessarily a separate file.

2020-12-23 14:39 UTC, NaamanTsur approved these changes

2020-12-23 14:41 UTC, ItayBenMoshe approved these changes

2020-12-23 14:42 UTC, merged